### PR TITLE
Update ecmascript and http

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Make compatible with Meteor 2.3 by updating the http package. Merge and release after Meteor 2.3 comes out.

### CODE REVIEW

**Comment by perbergland** [comment]
Can you release a beta version of this? I currently cannot verify that 2.3 works for me since testing is borked

**Comment by perbergland** [comment]
Nevermind, I’ll clone git@github.com:StorytellerCZ/meteor-mocha.git into packages and test locally

**Comment by perbergland** [comment]
Pls merge and release, this blocks upgrading to meteor 2.3. Thanks!

**Comment by StorytellerCZ** [comment]
@aldeed @SimonSimCity can one of you do this?

**Review by aldeed — APPROVED** [review]

**Pull request merged**
